# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tp3.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttp3.proto\x12\x06Tp3Rpc\"\"\n\rClientMessage\x12\x11\n\tProcessId\x18\x01 \x01(\x05\":\n\x0eGrantedMessage\x12\x17\n\x0fTargetProcessId\x18\x01 \x01(\x05\x12\x0f\n\x07granted\x18\x02 \x01(\x08\":\n\x0fReleaseResponse\x12\x17\n\x0fTargetProcessId\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\x08\x32\x81\x01\n\x06Tp3RPC\x12:\n\x07Request\x12\x15.Tp3Rpc.ClientMessage\x1a\x16.Tp3Rpc.GrantedMessage\"\x00\x12;\n\x07Release\x12\x15.Tp3Rpc.ClientMessage\x1a\x17.Tp3Rpc.ReleaseResponse\"\x00\x42\nZ\x08./serverb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tp3_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010./server'
  _globals['_CLIENTMESSAGE']._serialized_start=21
  _globals['_CLIENTMESSAGE']._serialized_end=55
  _globals['_GRANTEDMESSAGE']._serialized_start=57
  _globals['_GRANTEDMESSAGE']._serialized_end=115
  _globals['_RELEASERESPONSE']._serialized_start=117
  _globals['_RELEASERESPONSE']._serialized_end=175
  _globals['_TP3RPC']._serialized_start=178
  _globals['_TP3RPC']._serialized_end=307
# @@protoc_insertion_point(module_scope)
